# Generated by Django 2.0.2 on 2018-06-17 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listing.Task'),
        ),
    ]
